name: Build and Upload Executable

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [macos-14, macos-13, ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Executable with PyInstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.1'
          spec: 'go.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'CGo-${{ runner.os }}-${{ runner.arch }}'
          options: '--onefile --name CGo --windowed'
