name: Build and Upload Executable

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.1'
          spec: 'go.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'CGo'
          options: --onefile, --name "CGo", --windowed, 
